#########################
# ACNTECH Configuration #
#########################
acntech:
  api:
    client-context-path: /api/vagrant/boxes
  file:
    default-file-name: image.box
    upload-dir: /tmp/vagrant-repository/uploads

########################
# SPRING Configuration #
########################
spring:
  application:
    name: vagrant-repository-manager-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
      file-size-threshold: 2KB
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: false
  flyway:
    clean-on-validation-error: true
    out-of-order: true

# Logging
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: ["info", "health"]
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
