########################
# SPRING Configuration #
########################
spring:
  application:
    name: vagrant-repository-manager-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2100MB
      file-size-threshold: 2KB
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  h2:
    console:
      enabled: false

# Logging
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

#########################
# ACNTECH Configuration #
#########################
acntech:
  file:
    root-context-path: /api/vagrant/boxes
    default-file-name: image.box
    upload-dir: /tmp/vagrant-repository-manager/uploads
