########################
# SPRING Configuration #
########################
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vagrant-repository;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  flyway:
    locations:
      - classpath:db/vendor/h2
      - classpath:db/migration

# Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

