FROM acntechie/vagrant-repository-api

RUN wget --no-cookies \
         --no-check-certificate \
         http://central.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar \
         -O /docker-java-home/jre/lib/ext/postgresql.jar
