version: '3.5'

services:
  database:
    image: postgres
    container_name: vagrant-repository-database
    hostname: database
    domainname: acntech.local
    environment:
      - POSTGRES_DB=vagrant_repository
      - POSTGRES_USER=vagrant_repository
      - POSTGRES_PASSWORD=64nd4lf
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - vagrant_repository

volumes:
  database:
    name: vagrant-repository-database

networks:
  vagrant_repository:
    name: vagrant-repository
