version: '3.5'

services:
  gui:
    image: vagrant-repository-gui
#    image: acntechie/vagrant-repository-gui
    container_name: vagrant-repository-gui
    hostname: gui
    domainname: vagrant-repository.local
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
    ports:
      - 80:80
    networks:
      - vagrant_repository

  api:
    image: vagrant-repository-api
#    image: acntechie/vagrant-repository-api
    container_name: vagrant-repository-api
    hostname: api
    domainname: vagrant-repository.local
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    ports:
      - 8080:8080
    volumes:
      - ./postgresql-42.2.5.jar:/docker-java-home/jre/lib/ext/postgresql.jar
    networks:
      - vagrant_repository

  database:
    image: postgres
    container_name: vagrant-repository-database
    hostname: database
    domainname: vagrant-repository.local
    environment:
      - POSTGRES_DB=vagrant-repository
      - POSTGRES_USER=vagrant-repository
      - POSTGRES_PASSWORD=64nd4lf
    ports:
      - 5432:5432
    networks:
      - vagrant_repository

networks:
  vagrant_repository:
    name: vagrant-repository