version: '3.7'

services:
  postgres:
    image: postgres
    container_name: acntech.postgres
    environment:
      - POSTGRES_DB=vagrant_repository
      - POSTGRES_USER=vagrant_repository
      - POSTGRES_PASSWORD=64nd4lf
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres:
    name: acntech.postgres

networks:
  postgres:
    name: acntech.postgres
