version: '3.5'

services:
  gui:
    build:
      context: manager-gui
      args:
        API_URL: http://api:8080
    image: vagrant-repository-manager-gui:latest
    container_name: vagrant-repository-manager-gui
    hostname: gui
    domainname: manager.local
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - vagrant_repository_manager

  api:
    build: manager-api
    image: vagrant-repository-manager-api:latest
    container_name: vagrant-repository-manager-api
    hostname: api
    domainname: manager.local
    ports:
      - 8080:8080
    networks:
      - vagrant_repository_manager

networks:
  vagrant_repository_manager:
    name: vagrant-repository-manager