#########################
# ACNTECH Configuration #
#########################
acntech:
  keys:
    public-key: ${ACNTECH_PUBLIC_KEY:classpath:public.pem}
    private-key: ${ACNTECH_PRIVATE_KEY:classpath:private.pem}
  storage:
    file-name: image.box
    upload-path: ${ACNTECH_STORAGE_UPLOAD_PATH}
    overwrite-existing-files: true


########################
# SPRING Configuration #
########################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include:
          - info
          - health
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

# Logging
logging:
  level:
    root: WARN
    org.springframework: ERROR
    org.jooq.Constants: WARN
    no.acntech: WARN
