#########################
# ACNTECH Configuration #
#########################
acntech:
  keys:
    public-key: classpath:public.pem
    private-key: classpath:private.pem
  security:
    cookie:
      name: ACNTECH_SESSION
      max-age: -1 # -1 = no expiry
      http-only: true # Having this as false is a big security vulnerability
  storage:
    file-name: image.box
    upload-path: /tmp/vagrant-repository/uploads
    overwrite-existing-files: true

########################
# SPRING Configuration #
########################
spring:
  # Servlet
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
      file-size-threshold: 2KB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vagrant_repository
    username: vagrant_repository
    password: 64nd4lf

# Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"

### Server ###
server:
  error:
    include-stacktrace: ALWAYS

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.jooq.Constants: WARN
    no.acntech: DEBUG
