########################
# SPRING Configuration #
########################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vagrant_repository
    username: vagrant_repository
    password: 64nd4lf

# Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.jooq.Constants: WARN
    no.acntech: DEBUG
