FROM acntechie/vagrant-repository-api

RUN wget --no-cookies \
         --no-check-certificate \
         http://central.maven.org/maven2/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar \
         -O /docker-java-home/jre/lib/ext/mysql-connector-java.jar
