version: '3.5'

services:
  gui:
    image: acntechie/vagrant-repository-gui
    container_name: vagrant-repository-gui
    hostname: gui
    domainname: vagrant-repository.local
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
    ports:
      - 80:80
    networks:
      - vagrant_repository

  api:
    build: .
    image: acntechie/vagrant-repository-api:mysql
    container_name: vagrant-repository-api
    hostname: api
    domainname: vagrant-repository.local
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - 8080:8080
    networks:
      - vagrant_repository

  database:
    image: mariadb
    container_name: vagrant-repository-database
    hostname: database
    domainname: vagrant-repository.local
    environment:
      - MYSQL_DATABASE=vagrant-repository
      - MYSQL_USER=vagrant-repository
      - MYSQL_PASSWORD=64nd4lf
      - MYSQL_ROOT_PASSWORD=5m4u6
    ports:
      - 3306:3306
    networks:
      - vagrant_repository

networks:
  vagrant_repository:
    name: vagrant-repository