version: '3.5'

services:
  gui:
    image: acntechie/vagrant-repository-gui
    container_name: vagrant-repository-gui
    hostname: gui
    domainname: vagrant-repository.local
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
    ports:
      - 80:80
    networks:
      - vagrant_repository

  api:
    build: .
    image: acntechie/vagrant-repository-api:oracle
    container_name: vagrant-repository-api
    hostname: api
    domainname: vagrant-repository.local
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
    ports:
      - 8080:8080
    networks:
      - vagrant_repository

  database:
    image: # Find an Oracle XE 18c image
    container_name: vagrant-repository-database
    hostname: database
    domainname: vagrant-repository.local
    environment:
      - ORACLE_DB=vagrant-repository
      - ORACLE_USER=vagrant-repository
      - ORACLE_PASSWORD=64nd4lf
    ports:
      - 1521:1521
    networks:
      - vagrant_repository

networks:
  vagrant_repository:
    name: vagrant-repository