CREATE TABLE GROUPS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(50 CHAR)         NOT NULL
, DESCRIPTION                               VARCHAR2(4000 CHAR)
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT GROUPS_PK                      PRIMARY KEY (ID)
, CONSTRAINT GROUPS_NAME_UC                 UNIQUE (NAME)
);

CREATE TABLE BOXES
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(50 CHAR)         NOT NULL
, DESCRIPTION                               VARCHAR2(4000 CHAR)
, GROUP_ID                                  NUMBER(19)                NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT BOXES_PK                       PRIMARY KEY (ID)
, CONSTRAINT BOXES_NAME_GROUP_ID_UC         UNIQUE (NAME, GROUP_ID)
, CONSTRAINT GROUP_ID_FK                    FOREIGN KEY (GROUP_ID)    REFERENCES GROUPS (ID)
);

CREATE TABLE VERSIONS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(50 CHAR)         NOT NULL
, DESCRIPTION                               VARCHAR2(4000 CHAR)
, BOX_ID                                    NUMBER(19)                NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT VERSIONS_PK                    PRIMARY KEY (ID)
, CONSTRAINT VERSIONS_NAME_BOX_ID_UC        UNIQUE (NAME, BOX_ID)
, CONSTRAINT BOX_ID_FK                      FOREIGN KEY (BOX_ID)      REFERENCES BOXES (ID)
);

CREATE TABLE PROVIDERS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, PROVIDER_TYPE                             VARCHAR2(50 CHAR)         NOT NULL
, SIZE                                      NUMBER(19)
, CHECKSUM_TYPE                             VARCHAR2(10 CHAR)
, CHECKSUM                                  VARCHAR2(100 CHAR)
, VERSION_ID                                NUMBER(19)                NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PROVIDERS_PK                   PRIMARY KEY (ID)
, CONSTRAINT PROVIDERS_NAME_VERSION_ID_UC   UNIQUE (PROVIDER_TYPE, VERSION_ID)
, CONSTRAINT VERSION_ID_FK                  FOREIGN KEY (VERSION_ID)  REFERENCES VERSIONS (ID)
);
